/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Status = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'planned' : null };
export type Status__1 = { 'won' : null } |
  { 'closed' : null } |
  { 'lost' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Status__2 = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface T {
  'id' : bigint,
  'plannedDate' : bigint,
  'status' : Status,
  'completedAt' : bigint,
  'clientId' : bigint,
  'userId' : Principal,
  'purpose' : string,
  'completionNotes' : string,
}
export interface T__1 {
  'id' : bigint,
  'status' : Status__1,
  'title' : string,
  'clientId' : bigint,
  'date' : bigint,
  'createdBy' : Principal,
  'type' : string,
  'description' : string,
  'updatedAt' : bigint,
  'amount' : [] | [bigint],
}
export interface T__2 {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'email' : string,
  'updatedAt' : bigint,
  'company' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface T__3 {
  'id' : bigint,
  'status' : Status__2,
  'dailyAllowance' : bigint,
  'locationsVisited' : string,
  'userId' : Principal,
  'date' : bigint,
  'travelAllowance' : bigint,
  'submittedAt' : bigint,
  'notes' : string,
  'adminRemarks' : string,
}
export interface T__4 { 'name' : string, 'createdAt' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveClaim' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[T__2], bigint>,
  'createInteraction' : ActorMethod<[T__1], bigint>,
  'createVisitLog' : ActorMethod<[T], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteInteraction' : ActorMethod<[bigint], undefined>,
  'deleteVisitLog' : ActorMethod<[bigint], undefined>,
  'getAllClaims' : ActorMethod<[], Array<T__3>>,
  'getAllClients' : ActorMethod<[], Array<T__2>>,
  'getAllInteractions' : ActorMethod<[], Array<T__1>>,
  'getAllVisits' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [T__4]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClaimsForCaller' : ActorMethod<[], Array<T__3>>,
  'getClaimsSummaryPerStaff' : ActorMethod<
    [],
    Array<
      [Principal, { 'totalApprovedAmount' : bigint, 'totalSubmitted' : bigint }]
    >
  >,
  'getClient' : ActorMethod<[bigint], [] | [T__2]>,
  'getInteraction' : ActorMethod<[bigint], [] | [T__1]>,
  'getInteractionsSummary' : ActorMethod<
    [],
    {
      'won' : bigint,
      'closed' : bigint,
      'lost' : bigint,
      'open' : bigint,
      'inProgress' : bigint,
    }
  >,
  'getPipelineStats' : ActorMethod<
    [],
    {
      'offer' : bigint,
      'order' : bigint,
      'inquiry' : bigint,
      'followup' : bigint,
    }
  >,
  'getTotalClientsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [T__4]>,
  'getVisitLogsCountPerStaff' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getVisitsForCaller' : ActorMethod<[], Array<T>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectClaim' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[T__4], undefined>,
  'submitClaim' : ActorMethod<[T__3], bigint>,
  'updateClient' : ActorMethod<[bigint, T__2], undefined>,
  'updateInteraction' : ActorMethod<[bigint, T__1], undefined>,
  'updateVisitLog' : ActorMethod<[bigint, T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];