/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T__2 = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Status__1 = IDL.Variant({
  'won' : IDL.Null,
  'closed' : IDL.Null,
  'lost' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const T__1 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'title' : IDL.Text,
  'clientId' : IDL.Nat,
  'date' : IDL.Int,
  'createdBy' : IDL.Principal,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'amount' : IDL.Opt(IDL.Nat),
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'planned' : IDL.Null,
});
export const T = IDL.Record({
  'id' : IDL.Nat,
  'plannedDate' : IDL.Int,
  'status' : Status,
  'completedAt' : IDL.Int,
  'clientId' : IDL.Nat,
  'userId' : IDL.Principal,
  'purpose' : IDL.Text,
  'completionNotes' : IDL.Text,
});
export const Status__2 = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const T__3 = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__2,
  'dailyAllowance' : IDL.Nat,
  'locationsVisited' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : IDL.Int,
  'travelAllowance' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'notes' : IDL.Text,
  'adminRemarks' : IDL.Text,
});
export const T__4 = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveClaim' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func([T__2], [IDL.Nat], []),
  'createInteraction' : IDL.Func([T__1], [IDL.Nat], []),
  'createVisitLog' : IDL.Func([T], [IDL.Nat], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteInteraction' : IDL.Func([IDL.Nat], [], []),
  'deleteVisitLog' : IDL.Func([IDL.Nat], [], []),
  'getAllClaims' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
  'getAllInteractions' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getAllVisits' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T__4)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaimsForCaller' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getClaimsSummaryPerStaff' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Record({
              'totalApprovedAmount' : IDL.Nat,
              'totalSubmitted' : IDL.Nat,
            }),
          )
        ),
      ],
      ['query'],
    ),
  'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(T__2)], ['query']),
  'getInteraction' : IDL.Func([IDL.Nat], [IDL.Opt(T__1)], ['query']),
  'getInteractionsSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'won' : IDL.Nat,
          'closed' : IDL.Nat,
          'lost' : IDL.Nat,
          'open' : IDL.Nat,
          'inProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPipelineStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'offer' : IDL.Nat,
          'order' : IDL.Nat,
          'inquiry' : IDL.Nat,
          'followup' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTotalClientsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__4)], ['query']),
  'getVisitLogsCountPerStaff' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getVisitsForCaller' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectClaim' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([T__4], [], []),
  'submitClaim' : IDL.Func([T__3], [IDL.Nat], []),
  'updateClient' : IDL.Func([IDL.Nat, T__2], [], []),
  'updateInteraction' : IDL.Func([IDL.Nat, T__1], [], []),
  'updateVisitLog' : IDL.Func([IDL.Nat, T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T__2 = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Status__1 = IDL.Variant({
    'won' : IDL.Null,
    'closed' : IDL.Null,
    'lost' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const T__1 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'title' : IDL.Text,
    'clientId' : IDL.Nat,
    'date' : IDL.Int,
    'createdBy' : IDL.Principal,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'amount' : IDL.Opt(IDL.Nat),
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'planned' : IDL.Null,
  });
  const T = IDL.Record({
    'id' : IDL.Nat,
    'plannedDate' : IDL.Int,
    'status' : Status,
    'completedAt' : IDL.Int,
    'clientId' : IDL.Nat,
    'userId' : IDL.Principal,
    'purpose' : IDL.Text,
    'completionNotes' : IDL.Text,
  });
  const Status__2 = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const T__3 = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__2,
    'dailyAllowance' : IDL.Nat,
    'locationsVisited' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : IDL.Int,
    'travelAllowance' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'notes' : IDL.Text,
    'adminRemarks' : IDL.Text,
  });
  const T__4 = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveClaim' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func([T__2], [IDL.Nat], []),
    'createInteraction' : IDL.Func([T__1], [IDL.Nat], []),
    'createVisitLog' : IDL.Func([T], [IDL.Nat], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteInteraction' : IDL.Func([IDL.Nat], [], []),
    'deleteVisitLog' : IDL.Func([IDL.Nat], [], []),
    'getAllClaims' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
    'getAllInteractions' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getAllVisits' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T__4)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaimsForCaller' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getClaimsSummaryPerStaff' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Record({
                'totalApprovedAmount' : IDL.Nat,
                'totalSubmitted' : IDL.Nat,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(T__2)], ['query']),
    'getInteraction' : IDL.Func([IDL.Nat], [IDL.Opt(T__1)], ['query']),
    'getInteractionsSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'won' : IDL.Nat,
            'closed' : IDL.Nat,
            'lost' : IDL.Nat,
            'open' : IDL.Nat,
            'inProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPipelineStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'offer' : IDL.Nat,
            'order' : IDL.Nat,
            'inquiry' : IDL.Nat,
            'followup' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTotalClientsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T__4)], ['query']),
    'getVisitLogsCountPerStaff' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getVisitsForCaller' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectClaim' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([T__4], [], []),
    'submitClaim' : IDL.Func([T__3], [IDL.Nat], []),
    'updateClient' : IDL.Func([IDL.Nat, T__2], [], []),
    'updateInteraction' : IDL.Func([IDL.Nat, T__1], [], []),
    'updateVisitLog' : IDL.Func([IDL.Nat, T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };