/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface T__3 {
    id: bigint;
    status: Status__2;
    dailyAllowance: bigint;
    locationsVisited: string;
    userId: Principal;
    date: bigint;
    travelAllowance: bigint;
    submittedAt: bigint;
    notes: string;
    adminRemarks: string;
}
export interface T__2 {
    id: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    email: string;
    updatedAt: bigint;
    company: string;
    address: string;
    notes: string;
    phone: string;
}
export interface T {
    id: bigint;
    plannedDate: bigint;
    status: Status;
    completedAt: bigint;
    clientId: bigint;
    userId: Principal;
    purpose: string;
    completionNotes: string;
}
export interface T__1 {
    id: bigint;
    status: Status__1;
    title: string;
    clientId: bigint;
    date: bigint;
    createdBy: Principal;
    type: string;
    description: string;
    updatedAt: bigint;
    amount?: bigint;
}
export interface T__4 {
    name: string;
    createdAt: bigint;
}
export enum Status {
    cancelled = "cancelled",
    completed = "completed",
    planned = "planned"
}
export enum Status__1 {
    won = "won",
    closed = "closed",
    lost = "lost",
    open = "open",
    inProgress = "inProgress"
}
export enum Status__2 {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveClaim(id: bigint, remarks: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClient(client: T__2): Promise<bigint>;
    createInteraction(interaction: T__1): Promise<bigint>;
    createVisitLog(visit: T): Promise<bigint>;
    deleteClient(id: bigint): Promise<void>;
    deleteInteraction(id: bigint): Promise<void>;
    deleteVisitLog(id: bigint): Promise<void>;
    getAllClaims(): Promise<Array<T__3>>;
    getAllClients(): Promise<Array<T__2>>;
    getAllInteractions(): Promise<Array<T__1>>;
    getAllVisits(): Promise<Array<T>>;
    getCallerUserProfile(): Promise<T__4 | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClaimsForCaller(): Promise<Array<T__3>>;
    getClaimsSummaryPerStaff(): Promise<Array<[Principal, {
            totalApprovedAmount: bigint;
            totalSubmitted: bigint;
        }]>>;
    getClient(id: bigint): Promise<T__2 | null>;
    getInteraction(id: bigint): Promise<T__1 | null>;
    getInteractionsSummary(): Promise<{
        won: bigint;
        closed: bigint;
        lost: bigint;
        open: bigint;
        inProgress: bigint;
    }>;
    getPipelineStats(): Promise<{
        offer: bigint;
        order: bigint;
        inquiry: bigint;
        followup: bigint;
    }>;
    getTotalClientsCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<T__4 | null>;
    getVisitLogsCountPerStaff(): Promise<Array<[Principal, bigint]>>;
    getVisitsForCaller(): Promise<Array<T>>;
    isCallerAdmin(): Promise<boolean>;
    rejectClaim(id: bigint, remarks: string): Promise<void>;
    saveCallerUserProfile(profile: T__4): Promise<void>;
    submitClaim(claimInput: T__3): Promise<bigint>;
    updateClient(id: bigint, client: T__2): Promise<void>;
    updateInteraction(id: bigint, interaction: T__1): Promise<void>;
    updateVisitLog(id: bigint, visit: T): Promise<void>;
}
import type { Status as _Status, Status__1 as _Status__1, Status__2 as _Status__2, T as _T, T__1 as _T__1, T__2 as _T__2, T__3 as _T__3, T__4 as _T__4, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveClaim(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveClaim(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveClaim(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClient(arg0: T__2): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0);
            return result;
        }
    }
    async createInteraction(arg0: T__1): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInteraction(to_candid_T__1_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInteraction(to_candid_T__1_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVisitLog(arg0: T): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVisitLog(to_candid_T_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVisitLog(to_candid_T_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteInteraction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInteraction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInteraction(arg0);
            return result;
        }
    }
    async deleteVisitLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisitLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisitLog(arg0);
            return result;
        }
    }
    async getAllClaims(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClaims();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClaims();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllInteractions(): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInteractions();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInteractions();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVisits(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVisits();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVisits();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<T__4 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClaimsForCaller(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsForCaller();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsForCaller();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClaimsSummaryPerStaff(): Promise<Array<[Principal, {
            totalApprovedAmount: bigint;
            totalSubmitted: bigint;
        }]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsSummaryPerStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsSummaryPerStaff();
            return result;
        }
    }
    async getClient(arg0: bigint): Promise<T__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInteraction(arg0: bigint): Promise<T__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteraction(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteraction(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInteractionsSummary(): Promise<{
        won: bigint;
        closed: bigint;
        lost: bigint;
        open: bigint;
        inProgress: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractionsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractionsSummary();
            return result;
        }
    }
    async getPipelineStats(): Promise<{
        offer: bigint;
        order: bigint;
        inquiry: bigint;
        followup: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPipelineStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPipelineStats();
            return result;
        }
    }
    async getTotalClientsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalClientsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalClientsCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<T__4 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitLogsCountPerStaff(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitLogsCountPerStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitLogsCountPerStaff();
            return result;
        }
    }
    async getVisitsForCaller(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitsForCaller();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitsForCaller();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectClaim(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectClaim(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectClaim(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: T__4): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitClaim(arg0: T__3): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitClaim(to_candid_T__3_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitClaim(to_candid_T__3_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: T__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return result;
        }
    }
    async updateInteraction(arg0: bigint, arg1: T__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInteraction(arg0, to_candid_T__1_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInteraction(arg0, to_candid_T__1_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVisitLog(arg0: bigint, arg1: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisitLog(arg0, to_candid_T_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisitLog(arg0, to_candid_T_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Status__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Status__2_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__2): Status__2 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_T__3_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__3): T__3 {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_T_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__4]): T__4 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__2]): T__2 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__1]): T__1 | null {
    return value.length === 0 ? null : from_candid_T__1_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status__2;
    dailyAllowance: bigint;
    locationsVisited: string;
    userId: Principal;
    date: bigint;
    travelAllowance: bigint;
    submittedAt: bigint;
    notes: string;
    adminRemarks: string;
}): {
    id: bigint;
    status: Status__2;
    dailyAllowance: bigint;
    locationsVisited: string;
    userId: Principal;
    date: bigint;
    travelAllowance: bigint;
    submittedAt: bigint;
    notes: string;
    adminRemarks: string;
} {
    return {
        id: value.id,
        status: from_candid_Status__2_n14(_uploadFile, _downloadFile, value.status),
        dailyAllowance: value.dailyAllowance,
        locationsVisited: value.locationsVisited,
        userId: value.userId,
        date: value.date,
        travelAllowance: value.travelAllowance,
        submittedAt: value.submittedAt,
        notes: value.notes,
        adminRemarks: value.adminRemarks
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status__1;
    title: string;
    clientId: bigint;
    date: bigint;
    createdBy: Principal;
    type: string;
    description: string;
    updatedAt: bigint;
    amount: [] | [bigint];
}): {
    id: bigint;
    status: Status__1;
    title: string;
    clientId: bigint;
    date: bigint;
    createdBy: Principal;
    type: string;
    description: string;
    updatedAt: bigint;
    amount?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        date: value.date,
        createdBy: value.createdBy,
        type: value.type,
        description: value.description,
        updatedAt: value.updatedAt,
        amount: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    plannedDate: bigint;
    status: _Status;
    completedAt: bigint;
    clientId: bigint;
    userId: Principal;
    purpose: string;
    completionNotes: string;
}): {
    id: bigint;
    plannedDate: bigint;
    status: Status;
    completedAt: bigint;
    clientId: bigint;
    userId: Principal;
    purpose: string;
    completionNotes: string;
} {
    return {
        id: value.id,
        plannedDate: value.plannedDate,
        status: from_candid_Status_n25(_uploadFile, _downloadFile, value.status),
        completedAt: value.completedAt,
        clientId: value.clientId,
        userId: value.userId,
        purpose: value.purpose,
        completionNotes: value.completionNotes
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Status__2 {
    return "pending" in value ? Status__2.pending : "approved" in value ? Status__2.approved : "rejected" in value ? Status__2.rejected : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    closed: null;
} | {
    lost: null;
} | {
    open: null;
} | {
    inProgress: null;
}): Status__1 {
    return "won" in value ? Status__1.won : "closed" in value ? Status__1.closed : "lost" in value ? Status__1.lost : "open" in value ? Status__1.open : "inProgress" in value ? Status__1.inProgress : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    planned: null;
}): Status {
    return "cancelled" in value ? Status.cancelled : "completed" in value ? Status.completed : "planned" in value ? Status.planned : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__3>): Array<T__3> {
    return value.map((x)=>from_candid_T__3_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__1>): Array<T__1> {
    return value.map((x)=>from_candid_T__1_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n23(_uploadFile, _downloadFile, x));
}
function to_candid_Status__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Status__2_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__2): _Status__2 {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_T__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__1): _T__1 {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_T__3_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__3): _T__3 {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_T_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status__2;
    dailyAllowance: bigint;
    locationsVisited: string;
    userId: Principal;
    date: bigint;
    travelAllowance: bigint;
    submittedAt: bigint;
    notes: string;
    adminRemarks: string;
}): {
    id: bigint;
    status: _Status__2;
    dailyAllowance: bigint;
    locationsVisited: string;
    userId: Principal;
    date: bigint;
    travelAllowance: bigint;
    submittedAt: bigint;
    notes: string;
    adminRemarks: string;
} {
    return {
        id: value.id,
        status: to_candid_Status__2_n34(_uploadFile, _downloadFile, value.status),
        dailyAllowance: value.dailyAllowance,
        locationsVisited: value.locationsVisited,
        userId: value.userId,
        date: value.date,
        travelAllowance: value.travelAllowance,
        submittedAt: value.submittedAt,
        notes: value.notes,
        adminRemarks: value.adminRemarks
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status__1;
    title: string;
    clientId: bigint;
    date: bigint;
    createdBy: Principal;
    type: string;
    description: string;
    updatedAt: bigint;
    amount?: bigint;
}): {
    id: bigint;
    status: _Status__1;
    title: string;
    clientId: bigint;
    date: bigint;
    createdBy: Principal;
    type: string;
    description: string;
    updatedAt: bigint;
    amount: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_Status__1_n5(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        date: value.date,
        createdBy: value.createdBy,
        type: value.type,
        description: value.description,
        updatedAt: value.updatedAt,
        amount: value.amount ? candid_some(value.amount) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    plannedDate: bigint;
    status: Status;
    completedAt: bigint;
    clientId: bigint;
    userId: Principal;
    purpose: string;
    completionNotes: string;
}): {
    id: bigint;
    plannedDate: bigint;
    status: _Status;
    completedAt: bigint;
    clientId: bigint;
    userId: Principal;
    purpose: string;
    completionNotes: string;
} {
    return {
        id: value.id,
        plannedDate: value.plannedDate,
        status: to_candid_Status_n9(_uploadFile, _downloadFile, value.status),
        completedAt: value.completedAt,
        clientId: value.clientId,
        userId: value.userId,
        purpose: value.purpose,
        completionNotes: value.completionNotes
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    cancelled: null;
} | {
    completed: null;
} | {
    planned: null;
} {
    return value == Status.cancelled ? {
        cancelled: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.planned ? {
        planned: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__2): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Status__2.pending ? {
        pending: null
    } : value == Status__2.approved ? {
        approved: null
    } : value == Status__2.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    won: null;
} | {
    closed: null;
} | {
    lost: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == Status__1.won ? {
        won: null
    } : value == Status__1.closed ? {
        closed: null
    } : value == Status__1.lost ? {
        lost: null
    } : value == Status__1.open ? {
        open: null
    } : value == Status__1.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
